export type SiteKey = "handyman" | "hvac";
export type Lang = "zh-TW" | "en";

export const activeSite: SiteKey = "hvac";

const phone = "626-252-4457";

const sharedAuth = {
  "zh-TW": {
    navCall: `電話 ${phone}`,
    langBtn: "English",
    userLabel: "使用者名稱",
    userPlaceholder: "請輸入使用者名稱",
    passLabel: "密碼",
    passPlaceholder: "請輸入密碼",
    loginBtn: "登入",
    registerBtn: "註冊",
    regNavBtn: "會員",
    forgotLink: "忘記密碼？",
    forgotTitle: "找回密碼",
    forgotBtn: "發送驗證碼",
    resetTitle: "重置密碼",
    resetBtn: "確認重置",
    tokenLabel: "驗證碼",
    tokenPlaceholder: "請輸入 6 位驗證碼",
    emailLabel: "電子郵箱",
    emailPlaceholder: "請輸入您的郵箱",
    switchLogin: "已有帳號？立即登入",
    switchRegister: "還沒有帳號？立即註冊",
    loginSuccess: "登入成功",
    loginFail: "登入失敗: ",
    nameLabel: "您的姓名",
    phoneLabel: "聯絡電話",
    dateLabel: "期望日期",
    descLabel: "問題描述",
    cancelBtn: "取消",
    submitBtn: "送出預約",
    submittingBtn: "送出中...",
  },
  en: {
    navCall: `Call ${phone}`,
    langBtn: "中文",
    userLabel: "Username",
    userPlaceholder: "Enter username",
    passLabel: "Password",
    passPlaceholder: "Enter password",
    loginBtn: "Login",
    registerBtn: "Register",
    regNavBtn: "Member",
    forgotLink: "Forgot password?",
    forgotTitle: "Recover Password",
    forgotBtn: "Send Code",
    resetTitle: "Reset Password",
    resetBtn: "Confirm Reset",
    tokenLabel: "Verification Code",
    tokenPlaceholder: "Enter 6-digit code",
    emailLabel: "Email Address",
    emailPlaceholder: "Enter email",
    switchLogin: "Already have an account? Login",
    switchRegister: "No account? Register",
    loginSuccess: "Login successful",
    loginFail: "Login failed: ",
    nameLabel: "Your Name",
    phoneLabel: "Phone Number",
    dateLabel: "Preferred Date",
    descLabel: "Issue Description",
    cancelBtn: "Cancel",
    submitBtn: "Submit Request",
    submittingBtn: "Submitting...",
  },
};

export const sites = {
  handyman: {
    brand: "Aixelis",
    phone,
    phoneHref: "tel:626-252-4457",
    navTagline: "Home & Business Repair",
    heroImage: "/aixelis-smart-home-hero.jpg",
    metadata: {
      title: "Aixelis | Handyman, Smart Home, Camera & Network Installation",
      description:
        "Aixelis provides handyman services for homes and businesses in Walnut, Los Angeles, Orange County, and Irvine, including appliance repair, business equipment, networking, security cameras, smart home devices, thermostat installation, small electrical, plumbing, and general repairs.",
      keywords: [
        "Aixelis",
        "handyman Walnut CA",
        "Walnut home repair",
        "Los Angeles handyman",
        "Orange County handyman",
        "Irvine handyman",
        "appliance repair",
        "appliance installation",
        "business equipment installation",
        "security camera installation",
        "video doorbell installation",
        "smart home installation",
        "smart lock installation",
        "Wi-Fi setup",
        "Ethernet cabling",
        "thermostat installation",
        "TV mounting",
        "furniture assembly",
        "door repair",
        "lock installation",
        "rental property maintenance",
        "shop repair",
      ],
    },
    translations: {
      "zh-TW": {
        ...sharedAuth["zh-TW"],
        heroTitle: "Aixelis 住宅與商家維修安裝服務",
        heroSub: "家電/商用設備 • 網路佈線 • 監控安裝 • 智能家居 • 小型水電 • 綜合維修",
        heroNote: "服務 Walnut 周邊、洛杉磯地區與 Orange County / Irvine，適合屋主、房東、店鋪、餐飲、倉庫與小型辦公室。",
        bookBtn: "立即預約",
        learnBtn: "查看服務",
        aboutTitle: "把住宅和商家那些「一直想修」的問題一次處理好",
        aboutDesc:
          "我們提供靈活、透明、好溝通的 handyman 服務。從住宅門鎖、燈具、家電小故障，到商家 Wi-Fi、網路線、攝影機、智能門鈴、溫控器、出風口與日常維修，先了解問題，再給出清楚方案與報價。",
        trustItems: ["透明報價", "快速回覆", "可做多項雜修", "中英文溝通"],
        servicesTitle: "常見服務項目",
        servicesDesc: "如果你的問題不在列表裡，也可以先提交描述，我們會判斷是否能處理。",
        serviceCards: [
          ["家電與商用設備", "住宅家電、店鋪常用設備、洗衣機、烘乾機、洗碗機、冰箱、油煙機、垃圾處理器等檢查、拆裝與小型維修。", "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&q=80&w=900"],
          ["網路與弱電", "住宅與商家 Wi-Fi 覆蓋、路由器設定、網路線佈線、牆面網口、機櫃整理與網路排查。", "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=900"],
          ["監控與智能設備", "住宅、店鋪與辦公室攝影機、NVR、智能門鈴、智能鎖、感應燈與基礎智能設備安裝設定。", "https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&q=80&w=900"],
          ["溫控器與出風口維護", "空調濾網、智能溫控器、出風口、冷暖氣基礎檢查與簡單維護；複雜 HVAC 維修會先評估是否適合承接。", "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&q=80&w=900"],
          ["小型水電雜修", "燈具、開關、插座、水龍頭、馬桶配件、漏水初步排查、浴室廚房常見小維修。", "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&q=80&w=900"],
          ["門窗牆面與五金", "門鎖、鉸鏈、窗簾、置物架、電視掛架、牆面修補、家具組裝與各類五金安裝。", "https://images.unsplash.com/photo-1606676539940-12768ce0e762?auto=format&fit=crop&q=80&w=900"],
        ],
        areaTitle: "服務區域",
        areaDesc: "以 Walnut 周邊為核心，也承接洛杉磯地區與 Orange County / Irvine 的家庭維修需求。",
        areas: ["Walnut 周邊", "Diamond Bar", "Rowland Heights", "洛杉磯地區", "Orange County", "Irvine 地區"],
        seoTitle: "常見搜尋服務",
        seoDesc: "Aixelis 可協助住宅與商家處理 handyman、家電維修、商用設備安裝、網路佈線、Wi-Fi 設定、監控攝影機安裝、智能門鈴、智能鎖、溫控器、家具組裝、出租房維護與店鋪維修等需求。",
        seoKeywords: ["handyman Walnut CA", "家電維修", "網路佈線", "監控安裝", "智能門鈴安裝", "智能鎖安裝", "家具組裝", "店鋪維修", "出租房維護"],
        processTitle: "預約流程",
        process: ["描述問題", "確認照片與地址", "估算方案與時間", "上門完成服務"],
        loginTitle: "Aixelis 會員登入",
        footer: "© 2026 Aixelis. All Rights Reserved.",
        modalTitle: "預約 Handyman 服務",
        serviceLabel: "需要什麼服務？",
        serviceOptions: ["家電 / 商用設備維修與安裝", "網路 / Wi-Fi / 佈線", "監控 / 門鈴 / 智能設備", "溫控器 / 出風口 / 濾網", "小型水電雜修", "門窗牆面與五金", "出租房 / 商家維護", "其他住宅或商家雜事"],
        descPlaceholder: "請描述住宅/商家類型、設備型號、故障情況、地址城市；如果方便，之後可補照片。",
        bookSuccess: "預約已送出，我們會盡快與您聯絡。",
      },
      en: {
        ...sharedAuth.en,
        heroTitle: "Aixelis Handyman Services for Homes & Businesses",
        heroSub: "Appliances & Business Equipment • Networking • Security Cameras • Smart Home • Small Electrical • Repairs",
        heroNote: "Serving Walnut, the greater Los Angeles area, and Orange County / Irvine for homeowners, landlords, shops, restaurants, warehouses, and small offices.",
        bookBtn: "Book Service",
        learnBtn: "View Services",
        aboutTitle: "Get home and business repairs off your list",
        aboutDesc:
          "We provide practical, transparent handyman help for jobs that are too small for a contractor but too important to ignore. From home repairs to shop Wi-Fi, cameras, smart devices, thermostats, vents, and everyday maintenance, tell us what is happening and we will help you decide the right next step.",
        trustItems: ["Clear pricing", "Fast response", "Multi-task visits", "English / Chinese"],
        servicesTitle: "Popular Services",
        servicesDesc: "If your issue is not listed, send a short description and we will let you know whether we can help.",
        serviceCards: [
          ["Appliances & Business Equipment", "Home appliances, common shop equipment, washer, dryer, dishwasher, refrigerator, range hood, garbage disposal inspection, installation, and minor repair.", "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&q=80&w=900"],
          ["Networking & Low Voltage", "Home and business Wi-Fi coverage, router setup, Ethernet cabling, wall jacks, network cleanup, and troubleshooting.", "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=900"],
          ["Cameras & Smart Devices", "Security cameras, NVR, video doorbells, smart locks, motion lights, and smart device setup for homes, shops, and offices.", "https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&q=80&w=900"],
          ["Thermostat & Vent Help", "Air filters, smart thermostats, vents, and basic heating or cooling checks. Larger HVAC repairs are reviewed before scheduling.", "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&q=80&w=900"],
          ["Small Electrical & Plumbing", "Lights, switches, outlets, faucets, toilet parts, basic leak checks, kitchen and bathroom small repairs.", "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&q=80&w=900"],
          ["Doors, Walls & Hardware", "Locks, hinges, curtain rods, shelves, TV mounts, drywall patching, furniture assembly, and hardware installs.", "https://images.unsplash.com/photo-1606676539940-12768ce0e762?auto=format&fit=crop&q=80&w=900"],
        ],
        areaTitle: "Service Area",
        areaDesc: "Walnut and nearby cities are the core service area, with availability across greater Los Angeles and Orange County / Irvine depending on schedule, distance, and job scope.",
        areas: ["Walnut Area", "Diamond Bar", "Rowland Heights", "Greater Los Angeles", "Orange County", "Irvine Area"],
        seoTitle: "Common Searches We Serve",
        seoDesc: "Aixelis helps homes and businesses with handyman service, appliance repair, business equipment installation, Ethernet cabling, Wi-Fi setup, security camera installation, video doorbells, smart locks, thermostat installation, furniture assembly, rental property maintenance, and shop repairs.",
        seoKeywords: ["handyman Walnut CA", "home repair near me", "appliance repair", "Ethernet cabling", "Wi-Fi setup", "security camera installation", "video doorbell installation", "smart lock installation", "furniture assembly", "shop repair"],
        processTitle: "How Booking Works",
        process: ["Describe the issue", "Confirm photos and address", "Estimate plan and timing", "Finish the job on site"],
        loginTitle: "Aixelis Member Login",
        footer: "© 2026 Aixelis. All Rights Reserved.",
        modalTitle: "Book Handyman Service",
        serviceLabel: "Service Needed",
        serviceOptions: ["Appliance / Business Equipment Repair & Install", "Network / Wi-Fi / Cabling", "Cameras / Doorbell / Smart Devices", "Thermostat / Vents / Filters", "Small Electrical & Plumbing", "Doors, Walls & Hardware", "Rental / Business Maintenance", "Other Home or Business Task"],
        descPlaceholder: "Describe whether this is for a home or business, the issue, model number, city, and any details. Photos can be shared later.",
        bookSuccess: "Request submitted. We will contact you soon.",
      },
    },
  },
  hvac: {
    brand: "Aixelis",
    phone,
    phoneHref: "tel:626-252-4457",
    navTagline: "HVAC • Electrical • Plumbing",
    heroImage: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&q=90&w=2200",
    metadata: {
      title: "Aixelis | HVAC, Electrical & Plumbing Services",
      description:
        "Aixelis provides HVAC, electrical, plumbing, thermostat, ventilation, air quality, and maintenance services for homes and businesses around Walnut, Los Angeles, Orange County, and Irvine.",
      keywords: [
        "Aixelis",
        "hvac contractor",
        "hvac repair",
        "hvac installation",
        "hvac maintenance",
        "ac services",
        "heating services",
        "thermostat services",
        "air quality services",
        "hvac ventilation",
        "residential hvac",
        "commercial hvac",
        "Walnut HVAC",
        "Los Angeles HVAC",
        "Orange County HVAC",
        "Irvine HVAC",
      ],
    },
    translations: {
      "zh-TW": {
        ...sharedAuth["zh-TW"],
        heroTitle: "Aixelis 專業 HVAC 暖通、電力與管道服務",
        heroSub: "暖通空調 • 冷暖氣維修 • 溫控器 • 電力維修 • 管道工程",
        heroNote: "服務 Walnut 周邊、洛杉磯地區與 Orange County / Irvine，為住宅與商家提供清楚報價、快速回覆與可靠維修。",
        bookBtn: "立即預約",
        learnBtn: "查看服務",
        aboutTitle: "為什麼選擇 Aixelis？",
        aboutDesc:
          "我們提供住宅與商家的 HVAC、電力與管道相關服務。無論是空調不冷、暖氣異常、溫控器更換、通風問題、漏水初步排查或小型電力維修，我們都會先了解情況，再提供清楚方案與報價。",
        trustItems: ["透明報價", "快速響應", "住宅與商家", "中英文溝通"],
        servicesTitle: "HVAC 與家庭商家維修服務",
        servicesDesc: "從空調、暖氣、通風到電力與管道小維修，先判斷問題，再安排合適服務。",
        serviceCards: [
          ["HVAC 暖通空調", "空調檢查、冷暖氣故障判斷、出風口、通風與系統基礎維護。", "https://images.unsplash.com/photo-1581094288338-2314dddb31b5?auto=format&fit=crop&q=80&w=900"],
          ["AC 維修與保養", "空調不冷、異音、濾網、排水、冷凝問題與季節性 tune up。", "https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?auto=format&fit=crop&q=80&w=900"],
          ["暖氣與熱泵", "Heating service、熱泵維修、暖氣基本檢查與常見故障排查。", "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&q=80&w=900"],
          ["溫控器與智能控制", "傳統溫控器、智能 thermostat 安裝設定與冷暖氣控制問題排查。", "https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&q=80&w=900"],
          ["電力服務", "燈具、開關、插座、面板基礎檢查與小型電力維修。", "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&q=80&w=900"],
          ["管道與排水", "水龍頭、馬桶配件、漏水初步排查、熱水器與排水常見問題。", "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&q=80&w=900"],
        ],
        areaTitle: "服務區域",
        areaDesc: "主要服務 Walnut、Diamond Bar、Rowland Heights，也承接洛杉磯地區與 Orange County / Irvine 的 HVAC、電力與管道需求。",
        areas: ["Walnut", "Diamond Bar", "Rowland Heights", "洛杉磯地區", "Orange County", "Irvine"],
        seoTitle: "常見 HVAC 搜尋服務",
        seoDesc: "Aixelis 可協助處理 hvac repair、ac services、hvac installation、hvac maintenance、hvac tune up、heating services、thermostat services、hvac ventilation、air quality services、residential hvac 與 commercial hvac 等需求。",
        seoKeywords: ["hvac contractor", "暖通空調", "熱泵維修", "ac services", "hvac installation", "hvac maintenance", "hvac repair", "hvac tune up", "heating services", "thermostat services", "air quality services", "commercial hvac"],
        processTitle: "預約流程",
        process: ["描述故障", "確認地址與照片", "評估服務方案", "安排上門處理"],
        loginTitle: "Aixelis 會員登入",
        footer: "© 2026 Aixelis Home Services. All Rights Reserved.",
        modalTitle: "預約 HVAC / 維修服務",
        serviceLabel: "需要什麼服務？",
        serviceOptions: ["HVAC 暖通空調", "AC 維修 / 保養", "暖氣 / 熱泵", "溫控器服務", "通風 / 空氣品質", "電力維修", "管道工程", "其他維修"],
        descPlaceholder: "請描述冷暖氣、空調、電力或管道問題；如有設備型號、照片、地址城市也請一起提供。",
        bookSuccess: "預約已成功送出，我們會盡快與您聯絡。",
      },
      en: {
        ...sharedAuth.en,
        heroTitle: "Expert HVAC, Electrical & Plumbing Services",
        heroSub: "HVAC • AC Repair • Heating • Thermostats • Electrical • Plumbing",
        heroNote: "Serving Walnut, greater Los Angeles, and Orange County / Irvine with clear pricing, fast response, and reliable home and business service.",
        bookBtn: "Book Service",
        learnBtn: "View Services",
        aboutTitle: "Why Choose Aixelis?",
        aboutDesc:
          "Aixelis helps homes and businesses with HVAC, electrical, and plumbing service needs. Whether your AC is not cooling, heating is inconsistent, a thermostat needs replacement, ventilation is weak, or a small electrical or plumbing issue needs attention, we start with the issue and provide a clear next step.",
        trustItems: ["Clear pricing", "Fast response", "Homes & businesses", "English / Chinese"],
        servicesTitle: "HVAC & Home Service Categories",
        servicesDesc: "From AC, heating, and ventilation to small electrical and plumbing work, we help diagnose the issue and schedule the right service.",
        serviceCards: [
          ["HVAC Services", "AC checks, heating issues, vents, ventilation, and basic HVAC system maintenance.", "https://images.unsplash.com/photo-1581094288338-2314dddb31b5?auto=format&fit=crop&q=80&w=900"],
          ["AC Repair & Maintenance", "Cooling issues, unusual noise, filters, drainage, condenser concerns, and seasonal tune ups.", "https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?auto=format&fit=crop&q=80&w=900"],
          ["Heating & Heat Pump", "Heating service, heat pump repair, basic heating checks, and common system troubleshooting.", "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&q=80&w=900"],
          ["Thermostat Services", "Standard and smart thermostat installation, setup, replacement, and temperature control troubleshooting.", "https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&q=80&w=900"],
          ["Electrical Services", "Lights, switches, outlets, basic panel checks, and small electrical repairs.", "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&q=80&w=900"],
          ["Plumbing Services", "Faucets, toilet parts, basic leak checks, water heater concerns, and common drain issues.", "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&q=80&w=900"],
        ],
        areaTitle: "Service Area",
        areaDesc: "Serving Walnut, Diamond Bar, Rowland Heights, greater Los Angeles, Orange County, and Irvine for HVAC, electrical, and plumbing service requests.",
        areas: ["Walnut", "Diamond Bar", "Rowland Heights", "Greater Los Angeles", "Orange County", "Irvine"],
        seoTitle: "Common HVAC Searches We Serve",
        seoDesc: "Aixelis helps with hvac repair, ac services, hvac installation, hvac maintenance, hvac tune up, heating services, thermostat services, hvac ventilation, air quality services, residential hvac, and commercial hvac requests.",
        seoKeywords: ["hvac contractor", "emergency hvac contractor", "ac services", "hvac installation", "hvac maintenance", "hvac repair", "hvac tune up", "heating services", "thermostat services", "air quality services", "residential hvac", "commercial hvac"],
        processTitle: "How Booking Works",
        process: ["Describe the issue", "Confirm photos and address", "Estimate the service plan", "Schedule on-site service"],
        loginTitle: "Aixelis Member Login",
        footer: "© 2026 Aixelis Home Services. All Rights Reserved.",
        modalTitle: "Book HVAC / Home Service",
        serviceLabel: "Service Needed",
        serviceOptions: ["HVAC Services", "AC Repair / Maintenance", "Heating / Heat Pump", "Thermostat Services", "Ventilation / Air Quality", "Electrical Services", "Plumbing Services", "Other Repair"],
        descPlaceholder: "Describe the HVAC, AC, heating, electrical, or plumbing issue. Include model number, photos, and city if available.",
        bookSuccess: "Request submitted. We will contact you soon.",
      },
    },
  },
} as const;

export const siteContent = sites[activeSite];
