export type SiteKey = "handyman" | "hvac";
export type Lang = "zh-TW" | "en";

export const activeSite: SiteKey = "hvac";

const phone = "626-252-4457";

const sharedAuth = {
  "zh-TW": {
    navCall: `電話 ${phone}`,
    langBtn: "English",
    userLabel: "使用者名稱",
    userPlaceholder: "請輸入使用者名稱",
    passLabel: "密碼",
    passPlaceholder: "請輸入密碼",
    loginBtn: "登入",
    registerBtn: "註冊",
    regNavBtn: "會員",
    forgotLink: "忘記密碼？",
    forgotTitle: "找回密碼",
    forgotBtn: "發送驗證碼",
    resetTitle: "重置密碼",
    resetBtn: "確認重置",
    tokenLabel: "驗證碼",
    tokenPlaceholder: "請輸入 6 位驗證碼",
    emailLabel: "電子郵箱",
    emailPlaceholder: "請輸入您的郵箱",
    switchLogin: "已有帳號？立即登入",
    switchRegister: "還沒有帳號？立即註冊",
    loginSuccess: "登入成功",
    loginFail: "登入失敗: ",
    nameLabel: "您的姓名",
    phoneLabel: "聯絡電話",
    dateLabel: "期望日期",
    descLabel: "問題描述",
    cancelBtn: "取消",
    submitBtn: "送出預約",
    submittingBtn: "送出中...",
  },
  en: {
    navCall: `Call ${phone}`,
    langBtn: "中文",
    userLabel: "Username",
    userPlaceholder: "Enter username",
    passLabel: "Password",
    passPlaceholder: "Enter password",
    loginBtn: "Login",
    registerBtn: "Register",
    regNavBtn: "Member",
    forgotLink: "Forgot password?",
    forgotTitle: "Recover Password",
    forgotBtn: "Send Code",
    resetTitle: "Reset Password",
    resetBtn: "Confirm Reset",
    tokenLabel: "Verification Code",
    tokenPlaceholder: "Enter 6-digit code",
    emailLabel: "Email Address",
    emailPlaceholder: "Enter email",
    switchLogin: "Already have an account? Login",
    switchRegister: "No account? Register",
    loginSuccess: "Login successful",
    loginFail: "Login failed: ",
    nameLabel: "Your Name",
    phoneLabel: "Phone Number",
    dateLabel: "Preferred Date",
    descLabel: "Issue Description",
    cancelBtn: "Cancel",
    submitBtn: "Submit Request",
    submittingBtn: "Submitting...",
  },
};

const handymanServiceCards = {
  "zh-TW": [
    ["家電與商用設備", "住宅家電、店鋪常用設備、洗衣機、烘乾機、洗碗機、冰箱、油煙機、垃圾處理器等檢查、拆裝與小型維修。", "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&q=80&w=900"],
    ["網路與弱電", "住宅與商家 Wi-Fi 覆蓋、路由器設定、網路線佈線、牆面網口、機櫃整理與網路排查。", "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=900"],
    ["監控與智能設備", "住宅、店鋪與辦公室攝影機、NVR、智能門鈴、智能鎖、感應燈與基礎智能設備安裝設定。", "https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&q=80&w=900"],
    ["溫控器與出風口維護", "空調濾網、智能溫控器、出風口、冷暖氣基礎檢查與簡單維護；複雜 HVAC 維修會先評估是否適合承接。", "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&q=80&w=900"],
    ["小型水電雜修", "燈具、開關、插座、水龍頭、馬桶配件、漏水初步排查、浴室廚房常見小維修。", "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&q=80&w=900"],
    ["門窗牆面與五金", "門鎖、鉸鏈、窗簾、置物架、電視掛架、牆面修補、家具組裝與各類五金安裝。", "https://images.unsplash.com/photo-1606676539940-12768ce0e762?auto=format&fit=crop&q=80&w=900"],
  ],
  en: [
    ["Appliances & Business Equipment", "Home appliances, common shop equipment, washer, dryer, dishwasher, refrigerator, range hood, garbage disposal inspection, installation, and minor repair.", "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&q=80&w=900"],
    ["Networking & Low Voltage", "Home and business Wi-Fi coverage, router setup, Ethernet cabling, wall jacks, network cleanup, and troubleshooting.", "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=900"],
    ["Cameras & Smart Devices", "Security cameras, NVR, video doorbells, smart locks, motion lights, and smart device setup for homes, shops, and offices.", "https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&q=80&w=900"],
    ["Thermostat & Vent Help", "Air filters, smart thermostats, vents, and basic heating or cooling checks. Larger HVAC repairs are reviewed before scheduling.", "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&q=80&w=900"],
    ["Small Electrical & Plumbing", "Lights, switches, outlets, faucets, toilet parts, basic leak checks, kitchen and bathroom small repairs.", "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&q=80&w=900"],
    ["Doors, Walls & Hardware", "Locks, hinges, curtain rods, shelves, TV mounts, drywall patching, furniture assembly, and hardware installs.", "https://images.unsplash.com/photo-1606676539940-12768ce0e762?auto=format&fit=crop&q=80&w=900"],
  ],
} as const;

const hvacServiceCards = {
  "zh-TW": [
    ["暖通空调 (HVAC)", "空调安装、热泵维修、通风系统清洁，确保您的家庭四季如春。", "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&q=80&w=900"],
    ["电力服务", "电路升级、面板维修、照明安装。安全第一，先评估再安排服务。", "https://images.unsplash.com/photo-1581094288338-2314dddb31b5?auto=format&fit=crop&q=80&w=900"],
    ["管道工程", "漏水修复、热水器更换、下水道疏通。快速上门，彻底解决问题。", "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&q=80&w=900"],
  ],
  en: [
    ["HVAC", "AC installation, heat pump repair, and ventilation system cleaning to keep your home comfortable through every season.", "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&q=80&w=900"],
    ["Electrical Service", "Circuit upgrades, panel repair, and lighting installation with safety-first service planning.", "https://images.unsplash.com/photo-1581094288338-2314dddb31b5?auto=format&fit=crop&q=80&w=900"],
    ["Plumbing", "Leak repair, water heater replacement, and drain cleaning with responsive on-site help.", "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&q=80&w=900"],
  ],
} as const;

export const sites = {
  handyman: {
    brand: "Aixelis",
    phone,
    phoneHref: "tel:626-252-4457",
    theme: "light",
    navTagline: "Home & Business Repair",
    heroImage: "/aixelis-smart-home-hero.jpg",
    metadata: {
      title: "Aixelis | Handyman, Smart Home, Camera & Network Installation",
      description:
        "Aixelis provides handyman services for homes and businesses in Walnut, Los Angeles, Orange County, and Irvine, including appliance repair, business equipment, networking, security cameras, smart home devices, thermostat installation, small electrical, plumbing, and general repairs.",
      keywords: ["Aixelis", "handyman Walnut CA", "Walnut home repair", "Los Angeles handyman", "Orange County handyman", "Irvine handyman", "appliance repair", "security camera installation", "smart home installation", "Wi-Fi setup", "Ethernet cabling", "thermostat installation", "furniture assembly", "shop repair"],
    },
    translations: {
      "zh-TW": {
        ...sharedAuth["zh-TW"],
        heroTitle: "Aixelis 住宅與商家維修安裝服務",
        heroSub: "家電/商用設備 • 網路佈線 • 監控安裝 • 智能家居 • 小型水電 • 綜合維修",
        heroNote: "服務 Walnut 周邊、洛杉磯地區與 Orange County / Irvine，適合屋主、房東、店鋪、餐飲、倉庫與小型辦公室。",
        bookBtn: "立即預約",
        learnBtn: "查看服務",
        aboutTitle: "把住宅和商家那些「一直想修」的問題一次處理好",
        aboutDesc: "我們提供靈活、透明、好溝通的 handyman 服務。從住宅門鎖、燈具、家電小故障，到商家 Wi-Fi、網路線、攝影機、智能門鈴、溫控器、出風口與日常維修，先了解問題，再給出清楚方案與報價。",
        trustItems: ["透明報價", "快速回覆", "可做多項雜修", "中英文溝通"],
        servicesTitle: "常見服務項目",
        servicesDesc: "如果你的問題不在列表裡，也可以先提交描述，我們會判斷是否能處理。",
        serviceCards: handymanServiceCards["zh-TW"],
        areaTitle: "服務區域",
        areaDesc: "以 Walnut 周邊為核心，也承接洛杉磯地區與 Orange County / Irvine 的家庭維修需求。",
        areas: ["Walnut 周邊", "Diamond Bar", "Rowland Heights", "洛杉磯地區", "Orange County", "Irvine 地區"],
        seoTitle: "常見搜尋服務",
        seoDesc: "Aixelis 可協助住宅與商家處理 handyman、家電維修、商用設備安裝、網路佈線、Wi-Fi 設定、監控攝影機安裝、智能門鈴、智能鎖、溫控器、家具組裝、出租房維護與店鋪維修等需求。",
        seoKeywords: ["handyman Walnut CA", "家電維修", "網路佈線", "監控安裝", "智能門鈴安裝", "智能鎖安裝", "家具組裝", "店鋪維修", "出租房維護"],
        processTitle: "預約流程",
        process: ["描述問題", "確認照片與地址", "估算方案與時間", "上門完成服務"],
        loginTitle: "Aixelis 會員登入",
        footer: "© 2026 Aixelis. All Rights Reserved.",
        modalTitle: "預約 Handyman 服務",
        serviceLabel: "需要什麼服務？",
        serviceOptions: ["家電 / 商用設備維修與安裝", "網路 / Wi-Fi / 佈線", "監控 / 門鈴 / 智能設備", "溫控器 / 出風口 / 濾網", "小型水電雜修", "門窗牆面與五金", "出租房 / 商家維護", "其他住宅或商家雜事"],
        descPlaceholder: "請描述住宅/商家類型、設備型號、故障情況、地址城市；如果方便，之後可補照片。",
        bookSuccess: "預約已送出，我們會盡快與您聯絡。",
      },
      en: {
        ...sharedAuth.en,
        heroTitle: "Aixelis Handyman Services for Homes & Businesses",
        heroSub: "Appliances & Business Equipment • Networking • Security Cameras • Smart Home • Small Electrical • Repairs",
        heroNote: "Serving Walnut, the greater Los Angeles area, and Orange County / Irvine for homeowners, landlords, shops, restaurants, warehouses, and small offices.",
        bookBtn: "Book Service",
        learnBtn: "View Services",
        aboutTitle: "Get home and business repairs off your list",
        aboutDesc: "We provide practical, transparent handyman help for jobs that are too small for a contractor but too important to ignore.",
        trustItems: ["Clear pricing", "Fast response", "Multi-task visits", "English / Chinese"],
        servicesTitle: "Popular Services",
        servicesDesc: "If your issue is not listed, send a short description and we will let you know whether we can help.",
        serviceCards: handymanServiceCards.en,
        areaTitle: "Service Area",
        areaDesc: "Walnut and nearby cities are the core service area, with availability across greater Los Angeles and Orange County / Irvine depending on schedule, distance, and job scope.",
        areas: ["Walnut Area", "Diamond Bar", "Rowland Heights", "Greater Los Angeles", "Orange County", "Irvine Area"],
        seoTitle: "Common Searches We Serve",
        seoDesc: "Aixelis helps homes and businesses with handyman service, appliance repair, business equipment installation, Ethernet cabling, Wi-Fi setup, security camera installation, video doorbells, smart locks, thermostat installation, furniture assembly, rental property maintenance, and shop repairs.",
        seoKeywords: ["handyman Walnut CA", "home repair near me", "appliance repair", "Ethernet cabling", "Wi-Fi setup", "security camera installation", "video doorbell installation", "smart lock installation", "furniture assembly", "shop repair"],
        processTitle: "How Booking Works",
        process: ["Describe the issue", "Confirm photos and address", "Estimate plan and timing", "Finish the job on site"],
        loginTitle: "Aixelis Member Login",
        footer: "© 2026 Aixelis. All Rights Reserved.",
        modalTitle: "Book Handyman Service",
        serviceLabel: "Service Needed",
        serviceOptions: ["Appliance / Business Equipment Repair & Install", "Network / Wi-Fi / Cabling", "Cameras / Doorbell / Smart Devices", "Thermostat / Vents / Filters", "Small Electrical & Plumbing", "Doors, Walls & Hardware", "Rental / Business Maintenance", "Other Home or Business Task"],
        descPlaceholder: "Describe whether this is for a home or business, the issue, model number, city, and any details. Photos can be shared later.",
        bookSuccess: "Request submitted. We will contact you soon.",
      },
    },
  },
  hvac: {
    brand: "Aixelis",
    phone,
    phoneHref: "tel:626-252-4457",
    theme: "dark",
    navTagline: "HVAC • Electrical • Plumbing",
    heroImage: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&q=90&w=2200",
    metadata: {
      title: "Aixelis | HVAC, Electrical & Plumbing Services",
      description:
        "Aixelis provides HVAC, electrical, and plumbing services in Walnut, Los Angeles, Orange County, and Irvine, including AC installation, heat pump repair, ventilation, electrical upgrades, panel repair, lighting, leak repair, water heaters, and drain service.",
      keywords: ["Aixelis", "HVAC service", "HVAC Walnut CA", "Los Angeles HVAC", "Orange County HVAC", "Irvine HVAC", "AC installation", "heat pump repair", "ventilation system cleaning", "electrical service", "panel repair", "lighting installation", "plumbing service", "leak repair", "water heater replacement", "drain cleaning"],
    },
    translations: {
      "zh-TW": {
        ...sharedAuth["zh-TW"],
        heroTitle: "专业 HVAC & 电力服务",
        heroSub: "洛杉矶资深团队 | 暖通空调 • 电工 • 管道工程",
        heroNote: "Aixelis 为 Walnut、洛杉矶、Orange County 与 Irvine 周边家庭和商家提供暖通空调、电力与管道工程服务。",
        bookBtn: "立即预约",
        learnBtn: "了解更多",
        aboutTitle: "专业团队处理 HVAC、电力与管道问题",
        aboutDesc: "这套内容来自 aixelis-next-study 旧版 HVAC 首页，重点服务为暖通空调、电力服务与管道工程。我们会先了解现场问题，再安排适合的服务方案。",
        trustItems: ["快速上门", "安全第一", "住宅与商家", "中英文沟通"],
        servicesTitle: "核心服务项目",
        servicesDesc: "旧版 HVAC 网站主推三类服务：暖通空调、电力服务、管道工程。",
        serviceCards: hvacServiceCards["zh-TW"],
        areaTitle: "服務區域",
        areaDesc: "以 Walnut 周边、洛杉矶、Orange County 与 Irvine 为主要服务范围，具体上门安排取决于距离、时间与工作内容。",
        areas: ["Walnut", "Diamond Bar", "Rowland Heights", "洛杉矶地区", "Orange County", "Irvine"],
        seoTitle: "常见 HVAC、电力与管道服务",
        seoDesc: "Aixelis 可协助处理 HVAC、暖通空调、空调安装、热泵维修、通风系统清洁、电力服务、电路升级、面板维修、照明安装、管道工程、漏水修复、热水器更换与下水道疏通等需求。",
        seoKeywords: ["HVAC", "暖通空调", "空调安装", "热泵维修", "通风系统清洁", "电力服务", "电路升级", "面板维修", "照明安装", "管道工程", "漏水修复", "热水器更换", "下水道疏通"],
        processTitle: "預約流程",
        process: ["描述问题", "确认地址与照片", "评估方案与时间", "上门处理"],
        loginTitle: "AIXELIS 会员登录",
        footer: "© 2026 AIXELIS Home Services. All Rights Reserved.",
        modalTitle: "预约 HVAC / 电力 / 管道服务",
        serviceLabel: "需要什麼服務？",
        serviceOptions: ["暖通空调 (HVAC)", "空调安装", "热泵维修", "通风系统清洁", "电力服务", "电路升级 / 面板维修", "照明安装", "管道工程", "漏水修复", "热水器更换", "下水道疏通"],
        descPlaceholder: "请描述 HVAC、电力或管道问题；如有设备型号、照片、地址城市也请一起提供。",
        bookSuccess: "預約已送出，我們會盡快與您聯絡。",
      },
      en: {
        ...sharedAuth.en,
        heroTitle: "Professional HVAC & Electrical Services",
        heroSub: "Los Angeles Service Team | HVAC • Electrical • Plumbing",
        heroNote: "Aixelis serves homes and businesses around Walnut, Los Angeles, Orange County, and Irvine with HVAC, electrical, and plumbing services.",
        bookBtn: "Book Now",
        learnBtn: "Learn More",
        aboutTitle: "HVAC, Electrical & Plumbing Help From Aixelis",
        aboutDesc: "This content follows the older aixelis-next-study HVAC homepage, focused on HVAC, electrical service, and plumbing work. Tell us what is happening and we will help evaluate the right service plan.",
        trustItems: ["Fast response", "Safety first", "Homes & businesses", "English / Chinese"],
        servicesTitle: "Core Services",
        servicesDesc: "The original HVAC site focused on three service areas: HVAC, electrical service, and plumbing.",
        serviceCards: hvacServiceCards.en,
        areaTitle: "Service Area",
        areaDesc: "Serving Walnut, Diamond Bar, Rowland Heights, greater Los Angeles, Orange County, and Irvine depending on schedule, distance, and job scope.",
        areas: ["Walnut", "Diamond Bar", "Rowland Heights", "Greater Los Angeles", "Orange County", "Irvine"],
        seoTitle: "Common HVAC, Electrical & Plumbing Searches",
        seoDesc: "Aixelis helps with HVAC service, AC installation, heat pump repair, ventilation system cleaning, electrical service, circuit upgrades, panel repair, lighting installation, plumbing, leak repair, water heater replacement, and drain cleaning.",
        seoKeywords: ["HVAC service", "AC installation", "heat pump repair", "ventilation system cleaning", "electrical service", "circuit upgrades", "panel repair", "lighting installation", "plumbing service", "leak repair", "water heater replacement", "drain cleaning"],
        processTitle: "How Booking Works",
        process: ["Describe the issue", "Confirm address and photos", "Estimate plan and timing", "Handle the service on site"],
        loginTitle: "AIXELIS Member Login",
        footer: "© 2026 AIXELIS Home Services. All Rights Reserved.",
        modalTitle: "Book HVAC / Electrical / Plumbing Service",
        serviceLabel: "Service Needed",
        serviceOptions: ["HVAC", "AC Installation", "Heat Pump Repair", "Ventilation System Cleaning", "Electrical Service", "Circuit Upgrade / Panel Repair", "Lighting Installation", "Plumbing", "Leak Repair", "Water Heater Replacement", "Drain Cleaning"],
        descPlaceholder: "Describe the HVAC, electrical, or plumbing issue. Include model number, photos, and city if available.",
        bookSuccess: "Request submitted. We will contact you soon.",
      },
    },
  },
} as const;

export const siteContent = sites[activeSite];
